apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: load
  namespace: staging
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: load
    spec:
      containers:
      - name: load
        image: vikingo/busybox:1.5
        imagePullPolicy: Always
        env:
          - name: URL
            value: "http://frontend"
          - name: METHOD
            value: "GET"
          - name: USERAGENT
            value: "Mozilla/5.0 (compatible; bingbot/2.$DATE; +http://www.bing.com/bingbot.htm)"
        command: ["/bin/sh", "./lb.sh"]
